INSERT INTO `tblFilmGenres`(`strGenre`) VALUES
("Action"),
("Adventure"),
("Comedy"),
("Crime"),
("Drama"),
("History"),
("Horro"),
("Musical"),
("Sci-Fi"),
("War"),
("Western"),
("International"),
("Biography"),
("Romance"),
("Thriller"),
("Sports"),
("Fantasy"),
("Animated"),
("Childrens- kids- Family"),
("Documentary");