INSERT INTO `tblRoleTypes`(`strRoleType`) VALUES(
"Protagonist"),
("Antagonist"),
("Ingenue"),
("Juvenile"),
("Supporting roles"),
("Principals"),
("Foil"),
("Straight part"),
("Heavy"),
("Typecasting"),
("Casting by type"),
("Ensemble"),
("Cameo"),
("Walk-on"),
("Bit part"),
("Internalizing"),
("Externalizing"),
("Concentrating"),
("Observing"),
("Playing the condition"),
("Playing the objectives"),
("Sharing a scene"),
("Giving a scene"),
("Turning a scene");